# Use the fast 2D rendering engine instead of heavy 3D GLX
backend = "xrender";

# Opacity settings (Keep the clean transparency)
active-opacity = 0.90;
inactive-opacity = 0.80;
frame-opacity = 0.90;

# Turn OFF the heavy blur math
blur-background = false;

vsync = true;
log-level = "warn";

